version: '3.8'

services:
  db:
    build: ./mariadb
    container_name: mariadb_sakila
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  app:
    image: mcr.microsoft.com/devcontainers/java:17
    container_name: app_desint
    volumes:
      - ..:/workspaces/Codi_Exercicis_Curs_DESINT:cached
    network_mode: service:db
    # Manté el contenidor actiu
    command: sleep infinity

volumes:
  mariadb_data:
